# Generated by Django 4.0.5 on 2022-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_project_image_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='project',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
